# The directory containing the source files to parse recursively
source:
  - ../css

# The directory that aigis will build to
dest: ../../public

# The assets needed to build the docs
# You may put doc related assets here too: images, css, etc.
dependencies:
  - ./aigis_assets
  #- ../../dist/css
  #- ../../dist/js
  #- ../../dist/aigis_assets

# The directory containing the tempalte files to generate pages
# It must contain 'layout.xxx' and 'index.xxx' (.ejs or .jade or .hbs)
template_dir: ./template_ejs
template_engine: ejs

index: ../../README.md

transform:
  - html
